title: "TORS"
version: "0.1"

system:
  templatesDir: resources/views/

places:
  place1:
    type: restaurant
    name: "Restauracja testowa"
    openHours:
      1:
        - ["8:00", "10:00"]
        - ["15:00", "19:00"]
      2:
        - ["8:00", "20:00"]
      3:
        - ["8:00", "20:00"]
      4:
        - ["8:00", "20:00"]
      5:
        - ["8:00", "20:00"]
    contacts:
      contact1:
        phone: 721527299
        address_city: Kraków
    structure:
      floor1:
        name: "Piętro 1"
        rooms:
          room1:
            name: "Sala 1"
            areas:
              area1:
                name: "Area 1"
                tables:
                  table1:
                    name: "Stolik 1"
                    seats: 5
              area2:
                name: "Area 2"
                tables: false
                seats: 5

  place2:
    type: cinema
    name: "Kino testowe"
    openHours: []
    structure:
          floor1:
            name: "II piętro"
            rooms:
              room1:
                name: "Sala niebieska"
                areas:
                  area1:
                    name: "Rząd 1"
                    tables: false
                    seats: 10
                  area2:
                    name: "Rząd 2"
                    tables: false
                    seats: 10